name: Create File Text

on: push

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
            - name: Create test.txt
              run: touch src/test.txt

            - name: Write "hello Khai"
              run: echo "hello Khai" > src/test.txt

            - name: Read test.txt
              run: cat src/test.txt
          