name: Multiple Jobs

on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Print Hello
              run: echo "Hello Khai"
        
    test: 
        needs: build

        runs-on: ubuntu-latest

        steps:
            - name: Test
              run: echo "thanh cong"