name: NodeSetup

on: push

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - uses: actions/setup-node@v4
              with: 
                node-version: 18
            
            - name: Check Node version
              run: node -v

            - name: Init npm
              run: npm init -y

        

