name: RunCode

on: push

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Debug files
              run: |
                pwd
                ls -R
            
            - name: Compile
              run: g++ src/*.cpp -o app
            
            - name: Run
              run: ./app