name: RunCode

on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: g++ app.cpp -o app && ./app

    test:
        needs: build
        runs-on: ubuntu-latest
        steps: 
            - run: echo "run success!!!"
            
